version: '3.8'

services:
  app:
    build: .
    # ports:
    #   - "3001:3001"
    network_mode: host
    environment:
      - NODE_ENV=production
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
   

 